### ISSUE TITLE
Cannot create a has many relation

### ISSUE THREAD

**Issue by mglidden** [versolearning/meteor-factory#14]
We have a case where a parent has a list of child ids. There's no way to specify that the child ID should be in an array – trying to do `[Factory.get("child")]` throws an error (`RangeError: Maximum call stack size exceeded`).

Test case:
```
Authors = new Meteor.Collection('authors');
Books = new Meteor.Collection('books');
Factory.define('author', Authors, {name: 'John Smith'});
Factory.define('book', Books, { authorIds: [Factory.get('author')] });
Factory.create("book")
```

throws the error instead of creating the book.

**Comment by dburles** [comment]
Hey @mglidden you're right this isn't currently supported, will take a look soon

**Comment by dburles** [comment]
Added in 0.4.0 - let me know how it goes

**Comment by mglidden** [comment]
Looks good – thanks!
