### ISSUE TITLE
Add ability to pass options to the factory definition

### ISSUE THREAD

**Issue by gferreri** [versolearning/meteor-factory#18]
Suppose I have a single collection where each document has a child array

```
{
   name: "Charles Dickens",
   books: [
      {  name: "Great Expectations"  },
      {  name: "A Tale of Two Cities" }
   ]
}
```

Now I want to be able to create a document with a specific number of books. I'd like to be able to have access to an options object within my factory functions. Like this:

```
Factory.define('authors', Authors, {
   name: faker.fake("{{name.lastName}}, {{name.firstName}}"),
   books: function (options) {
       _(options.bookCount).times( function (n) {
            return ({ name: faker.lorem.words() })
    }
}  
```

Then I could create documents like this:

`var author = Factory.create('authors', {}, { bookCount: 25})`

To create a document with 25 books.

**Comment by dburles** [comment]
Hey @gferreri interesting idea, an alternative would be to extend an existing factory e.g:

```js
Factory.define('authorWith5Books', Authors, Factory.extend('author', {
  // ...
}));
```
