### ISSUE TITLE
Simplify creating a Meteor user

### ISSUE THREAD

**Issue by BassT** [versolearning/meteor-factory#24]
Example factory for Meteor users:

    Factory.define('user', Meteor.users, {
      password: () => faker.internet.password(),
      emails: () => [{ address: () => faker.internet.email(), verified: true }],
    })

This returns a function when accessing `emails[0].address`. Related to test _Factory - Build - Array with an object containing a function_.

My workaround:
    
    const buildEmail = () => [{ address: faker.internet.email(), verified: true }];
    
    Factory.define('user', Meteor.users, {
      password: () => faker.internet.password(),
      emails: () => buildEmail(),
    })

**Comment by dburles** [comment]
Hey @BassT you can also just do:
```js
Factory.define('user', Meteor.users, {
  password: () => faker.internet.password(),
  emails: () => [{ address: faker.internet.email(), verified: true }],
});
```

**Comment by BassT** [comment]
@dburles That was my previous version. But I encountered problems with a unique index on the `address` field.

**Comment by dburles** [comment]
It'll generate a new email address each time you call `Factory.create` or `build`. Perhaps before what you had was `emails: [{ address: faker.internet.email(), verified: true }],`

**Comment by dburles** [comment]
...and in that case it will be the same email address each time

**Comment by BassT** [comment]
@dburles You're right. My bad. Didn't notice it was the return value of a function. All those braces -.-
