### ISSUE TITLE
Array of Objects using Factory.get

### ISSUE THREAD

**Issue by abate** [versolearning/meteor-factory#26]
I've the impression that this is yet another use case that it is not supported at the moment.
#15 and #14 seems related to this one, but not quite.

Running this `define` I get a `RangeError: Maximum call stack size exceeded` Error ...

```
Factory.define('fakeTeam',Volunteers.Collections.Teams,
  {
    'name': () -> faker.company.companyName()
    'visibility': 'public',
    'leads': () -> [ {'userId': Factory.get('fakeUser'), 'role': 'lead'} ]
    'tags': () -> [faker.lorem.words()],
    'parents':[],
  })
```

I can't find a better title to describe this problem ...

**Comment by dburles** [comment]
Hey @abate are you able to reproduce the exact issue in an isolated (fresh) Meteor application? If so, would you mind linking me to it on GitHub and I'll take a look

**Comment by abate** [comment]
There you go : https://github.com/abate/test-factory

meteor npm install --save simpl-schema
meteor npm install --save babel-runtime
meteor npm install --save meteor-node-stubs

(probably there is a way to do this automatically ...)

thank you !

**Comment by dburles** [comment]
Thanks, yes you just have to run `meteor npm install` and it will read the package.json

**Comment by dburles** [comment]
Looks like what you're trying to do isn't supported yet 😔, as you can see by this test: https://github.com/versolearning/meteor-factory/blob/master/factory_tests.js#L337-L346

In the meantime you can just do this:

```js
import { Random } from 'meteor/random';

Factory.define('fakeTeam', Teams, {
  'name': function() { return faker.company.companyName(); },
  'leads': function() { return [{'userId': Random.id(), 'role': 'lead'}]; }
});
```

The only downside to this would be if you wished to use `Factory.tree`, though I wouldn't imagine your intention would be to store the complete user document within the array.

**Comment by abate** [comment]
Ok ! thank you for your support :)

**Comment by abate** [comment]
Another solution might be something like : 

```
> getRandomUser = () ->
>   _.sample(Factory.get('fakeUser').collection.find().fetch())
```
and

`'leads': function() { return [{'userId': getRandomUser()._id, 'role': 'lead'}]; }`
