### ISSUE TITLE
Simple way for getting related objects in a single create call?

### ISSUE THREAD

**Issue by Floriferous** [versolearning/meteor-factory#29]
When you define a collection with relationships like this:

```js
Factory.define('book', Books, {
  authorId: Factory.get('author'),
  name: 'A book',
  year() { return _.random(1900, 2014); }
});
```

And then when calling:
```js
const book = Factory.create('book');
```

Is there a simpler way to get the `author` object that I'm missing? Or should I do this:

```js
const author = Authors.find({ _id: book.authorId });
```

**Comment by dburles** [comment]
@Floriferous pretty much that, you can also use the `tree` method to generate an object based on your factory definition, see here https://github.com/versolearning/meteor-factory/blob/master/factory_tests.js#L348-L361
