### ISSUE TITLE
Faster insertion

### ISSUE THREAD

**Issue by romainkoenig** [versolearning/meteor-factory#30]
Hello,
I am starting to use your package for my tests, and I would be interested to accelerate the insertions of fixtures. What do you think of theses proposition ? Is it possible in this repo or another ?

First, to insert in batch. Instead of passing an object we could pass an array of objects to the function Factory.create, and it would insert in batch with an insertMany or somethink like this ? But I am not sure it is possible with meteor or if we can use a newer version of mongo just for the tests.

Second, I saw that in the factory.create : you findOne on the new document and return it. Sometime it is useful ( to get the id for example ) but sometime we could just pass it, with a flag or an other function ?
```js
Factory._create = (name, doc) => {
  const collection = Factory.get(name).collection;
  const insertId = collection.insert(doc);
  // const record = collection.findOne(insertId); optional for an other function like fastICreate or with boolean and return nothing
  return record;
};
```

**Comment by dburles** [comment]
Hey @romainkoenig I think the best way to improve performance is to make use of the [stub-collections package](https://github.com/hwillson/meteor-stub-collections) that way, it'll never insert into mongo at all, only to a local in-memory collection. See more here: https://guide.meteor.com/testing.html#mocking-the-database

**Comment by romainkoenig** [comment]
Ok thanks, I'll need to read them several times but I'll try theses !
