### ISSUE TITLE
Inconsistent errors server-side, factory not created every time

### ISSUE THREAD

**Issue by Floriferous** [versolearning/meteor-factory#32]
I'm having lots of trouble making my tests run consistently every time, with errors coming from this package. It is very well possible that it is my fault, but I don't understand why.

This is one of the errors I see on the first run of my tests (though not every time), and not on a subsequent rerun of my tests, only on the server, never on the client:

```
Error: Cannot read property '_id' of undefined
    at makeRelation (packages/dburles:factory/factory.js:45:14)
    at packages/dburles:factory/factory.js:71:20
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at walk (packages/dburles:factory/factory.js:67:7)
    at Function.Factory._build (packages/dburles:factory/factory.js:97:3)
    at Function.Factory.create (packages/dburles:factory/factory.js:121:23)
    at Hook.beforeEach2 (imports/api/loanrequests/test/loanRequests.test.js:67:27)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)
```

On circle CI, this test keeps failing but with a timeout error:
`timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

These are the 3 factories that are involved in this error:

```js
// Top level
Factory.define('loanRequest', LoanRequests, {
  userId: Factory.get('user'),
  createdAt: () => new Date(),
  general: () => ({
    fortuneUsed: 250000,
    insuranceFortuneUsed: 0,
    partnersToAvoid: ['joe', 'john'],
  }),
  borrowers: [Factory.get('borrower')],
  property: () => ({ value: 1000000 }),
  files: () => ({}),
  logic: () => ({ auction: {}, lender: {}, verification: {}, step: 1 }),
  name: () => 'request name',
  emails: () => [],
});

// Linked
Factory.define('user', Meteor.users, {
  roles: () => 'user',
  emails: () => [{ address: chance.email(), verified: false }],
});

Factory.define('borrower', Borrowers, {
  userId: Factory.get('user'),
  createdAt: () => new Date(),
  expenses: () => [{ description: 'test', value: 1 }],
  files: () => ({}),
  logic: () => ({}),
});
```

And this is the structure of my test file:
```js
describe('loanRequests', function () {
  beforeEach(function beforeEach1() {
    // xolvio:cleaner
    resetDatabase();
  });

  describe('modifiers', () => {
    let request;
    beforeEach(function beforeEach2() {
      request = Factory.create('loanRequest');
    });

    it('should work', () => {
      // This is where it fails
      const id = request._id;

      // ..test..
    })
  });
});
```

**Comment by dburles** [comment]
Hey @Floriferous you might need to either set a longer timeout (see: https://mochajs.org/#timeouts) or better stub your collections using https://atmospherejs.com/hwillson/stub-collections

**Comment by Floriferous** [comment]
Seems like it might not be related to this package, but to meteor-mocha..

https://github.com/practicalmeteor/meteor-mocha/issues/79

**Comment by dburles** [comment]
yeah definitely, I'd make use of stub-collections if possible, your tests will run a *lot* faster

**Comment by dburles** [comment]
and in that case you probably won't have to worry about your tests timing out

**Comment by dburles** [comment]
https://guide.meteor.com/testing.html#mocking-the-database

**Comment by Floriferous** [comment]
It was indeed an error with stub collections taking an order of magnitude longer to stub on the first call. So I fixed this by stubbing and restoring my collections once before all tests. Thanks for your help!

**Comment by yanickrochon** [comment]
I have this issue, and it's not related to Mocha. I have installed the stub-collections package, but it does not help. The problem happens since Meteor 1.6 as my tests never shown anything like this before (that I recall). I see random errors happening, where `Factory.create` returns `undefined`.

No idea why. All my tests run inside a Fiber (`Meteor.bindEnvironment`) and (`Meteor.wrapAsync`)

**Comment by yanickrochon** [comment]
Nivermind, Meteor's documentation is not clear about how `Meteor.wrapAsync` actually work; I wrap my tests in `Meteor.startup` functions and it seems to work, now.
