### ISSUE TITLE
Factory.get returns Circular object

### ISSUE THREAD

**Issue by bvanderdrift** [versolearning/meteor-factory#33]
I am currently setting up a testing environment for a new project.

I am in the process of debugging some errors, and wanted to know what object `get` returned since it did not return what I expected. Upon printing in the console it printed `[Circular]`.

I slimmed down everything and ended up with this basic code that you would be able to use to reproduce the error.

```
import { Mongo } from 'meteor/mongo'
import { Factory } from 'meteor/dburles:factory';
import { assert } from 'chai';

describe('ItemTester', function() {
	let Items = new Mongo.Collection('items');

	beforeEach(function() {
		Factory.define('item', Items,
			{a: "b"}
		);
	});

	afterEach(function() {
		
	});

	it('Should load nodes by ID', function() {
		console.log(Factory.get('item'));
		assert.equal(1, 1);
	});
});
```

**Comment by dburles** [comment]
The `get` method just returns the instance of the factory. See https://github.com/versolearning/meteor-factory#get

**Comment by bvanderdrift** [comment]
I'm sorry, did not read the docs well enough.
